/*
  Project: Sales Analysis
  Step: Category Analysis
  Description: Queries used to evaluate revenue and volume performance by product category.
*/

USE db_salesg;

-- Objective: Identify total revenue generated by each category (used in "Revenue by Category" chart)
SELECT
    p.category,
    SUM(s.revenue) AS total_revenue
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Objective: Identify total units sold by each category
SELECT
    p.category,
    SUM(s.units) AS total_units
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_units DESC;

-- Objective: Find the category with the highest sales volume (units)
SELECT
    p.category,
    SUM(s.units) AS total_units
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_units DESC
LIMIT 1;

-- Objective: Find the category with the highest revenue generation
SELECT
    p.category,
    SUM(s.revenue) AS total_revenue
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC
LIMIT 1;

-- Objective: Monthly revenue trend by category (used in "Monthly Revenue Performance by Category" chart)
SELECT
    s.year,
    s.month,
    s.month_name,
    p.category,
    SUM(s.revenue) AS monthly_revenue
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY s.year, s.month, s.month_name, p.category
ORDER BY s.year, s.month;

-- Objective: Compare average ticket (revenue per unit) across categories,
-- to show that volume and revenue are different performance dimensions
SELECT
    p.category,
    SUM(s.revenue) AS total_revenue,
    SUM(s.units) AS total_units,
    SUM(s.revenue) / SUM(s.units) AS revenue_per_unit
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue_per_unit DESC;
